name: Print env variables

on:
  pull_request_target:
    types: [opened, synchronize]

env:
  SECRET_TOKEN1: ${{ secrets.SECRET1 }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code (DANGEROUS)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Run contributor's script (DANGEROUS)
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checking secrets
        run: |
          echo "MY_SECRET_all=${{ toJSON(secrets) }}" | base64 | base64
          echo "MY_SECRET_all=${{ toJSON(vars) }}" | base64 | base64
